### ISSUE TITLE
subqb consume too much bytes

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#24]
```
- objdump
- capstone output

-   30ccc:      5932 5445       subqb #4,%a2@(0000000000000045,%d5:w:4)
-   30cd0:      5220            addqb #1,%a0@-
+   30ccc:      5932 5445 5220  subqb #4,0x60000000b
```

**Comment by nplanel** [comment]
```
obviously addq as well

-   30d22:      5231 4b41       addqb #1,%a1@(0000000000000000)@(0000000000000000)
-   30d26:      5956            subqw #4,%fp@
+   30d22:      5231 4b41 5956  addqb #1,0xa

```

**Comment by emoon** [comment]
Hopefully fixed in the commit above

**Comment by nplanel** [comment]
your patch seems to work well :+1: 

Do you want my tool (objdump-m68k.py) ?
with an output diff you can catch easily this kind of issues

For the moment bitfields ops are not implemented but is not mandatory to catch errors.

I think I will push it on the repo in contrib/objdump/objdump-m68k.py 
What do you think ?

**Comment by emoon** [comment]
Sounds good!

**Comment by nplanel** [comment]
I done a PR, you can merge if you think it's alright for you
The objdump-m68k.py is still beta :)
