### ISSUE TITLE
ori is not decoded correctly

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#27]
```
- objdump
+ capstone

-   30cc4:      00be 8080 2047  oril #-2139086777,%d6
+   30cc4:      00be            .short 0x00be
+   30cc6:      8080            orl %d0,%d0
+   30cc8:      2047            moveal %d7,%a0
```

**Comment by emoon** [comment]
This one is interesting. I don't see anything obvious wrong with the code so I need to investigate a bit more then (currently at work)

**Comment by emoon** [comment]
So.. I think is actually something wrong with objdump/undefined in this case.

ori.l opcode is this:

![ori_format](https://cloud.githubusercontent.com/assets/350822/10026203/b443777e-6160-11e5-88c9-5bb12549a3dc.png)

Which means bit 7 will be set (Long) register will be 6 (d6) and when using vasm68k it indeeds generates this data:

```
0x0086
```
If I test this
```
ori.l #$44444,d6
```
This data is generated
```
0x0086 0x004 0x4444
```

Which makes sense and is correct.

**Comment by nplanel** [comment]
Your test is correct. Compiling 'oril #-2139086777,%d6' and dumping the code give me 0x0086 on the same toolchain.

I agree objdump should not dump the instruction, this is an objdump bug ; As the combo mode+reg didn't exist, only 0b111 + 0b000 or 0b111 + 0b001 are valid.

Why that's work in capstone, because in the implementation the opcode lookup table (build_opcode_table()) point to illegal when <ea> is not valid ; Thanks to valid_ea()

We should check size too (0b11 is not valid)

What this opcode will do on a bare metal 680000 ? That's the question ... maybe a m68k secret :)

**Comment by emoon** [comment]
I can try it on my Amiga and see what happens :)

**Comment by emoon** [comment]
I will close this issue as I think the code in Capstone is doing the right thing. I agree though that we can add stronger tests.
