### ISSUE TITLE
implement bkpt

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#33]
```
-   30efa:      484e            bkpt 6
+   30efa:      484e            .short 0x484e
```

**Comment by emoon** [comment]
Hum.. this is implemented here:

https://github.com/emoon/capstone/blob/next/arch/M68K/M68Kdasm.c#L1413

Make sure you test with 68010+ (otherwise this is a bug)

**Comment by nplanel** [comment]
yep you catch it, I wasn't testing with 68k+
