### ISSUE TITLE
illegal vs undecoded

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#43]
I think we should add a special undecoded instruction, when no opcode match.
Today is implemented as illegal instruction, but it's a real instruction that have a specific opcode.
Objdump make the difference between undecoded and illegal instruction.

Furthermore we should return this undecoded instruction when the instruction can't be decoded inside the instruction callback.

What do you think ?

**Comment by nplanel** [comment]
for example in the d68020_cpgen() when the 2nd word didn't match the spec

**Comment by emoon** [comment]
Agreed!

**Comment by emoon** [comment]
They way capstone did it before was to just print out dc.w <data> which makes sense to as that is what I'm used to. (I think objdump prints .short or something but I like dc.w <data> better) thoughts? not sure how the other backends in capstone deals with this.

**Comment by nplanel** [comment]
Ok I will implement that tomorrow when I got time.
Yes objdump (with it's ugly syntax) print .short ; I agree that dc.w looks better.
if mnemonic == "undecoded":
   print(".short 0x%04x" % (op.imm))
if(mnemonic == M68K_INS_UNDECODED)
   printf("dc.w 0x%04x" % (op.imm))

**Comment by emoon** [comment]
Looks good to me! I have been using $ mostly for hex as that is also what most (at least the ones I have used) assembler use for hex (while 0x is C)

**Comment by nplanel** [comment]
Usually asm is #dec or #$ hex or $ hex (6805 era)
I prefer # and #$

**Comment by emoon** [comment]
Yeah so the way I have used it is like

```asm
move.w #$fade,d0
```

```asm
some_data:
   dc.w $fade
```

So in this case (if we want to just represent data) i think just dc.w $data would better.

**Comment by nplanel** [comment]
done in commit https://github.com/emoon/capstone/commit/0ad4e55ea5824be138b91c459ed6a9f71603c29b
