### ISSUE TITLE
M68K_AM_AREGI_INDEX_8_BIT_DISP decoding is missing

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#48]

**Comment by nplanel** [comment]
- objdump
+ capstone

-   2:	3189 7854      	movew %a1,%a0@(0000000000000054,%d7:l)
+   2:	3189 7854      	movew %a1,0x800000009

**Comment by emoon** [comment]
Thank. Will take a look at this later today.

**Comment by emoon** [comment]
Should be fixed now
