### ISSUE TITLE
movew bitwise index register length is not correct (op.mem.index_reg seems not set)

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#49]
op.mem.index_reg is equal to 0

I assume a "op->mem.index_size = EXT_INDEX_LONG(extension) ? 1 : 0;" is missing somewhere
```
- objdump
+ capstone
 -  2:	3189 7854      	movew %a1,%a0@(0000000000000054,%d7:l)
+   2:	3189 7854      	movew %a1,%a0@(0000000000000054,%d7:w)
```

**Comment by emoon** [comment]
I assume this instruction is actually

```
move.w $54(a0,d7.l)
```

right?

**Comment by nplanel** [comment]
yes

**Comment by nplanel** [comment]
```
-   2:	5576 1ce9      	subqw #2,%fp@(ffffffffffffffe9,%d1:l:4)
+   2:	5576 1ce9      	subqw #2,%fp@(ffffffffffffffe9,%d1:w:4)
```

**Comment by emoon** [comment]
Should be fixed now

**Comment by nplanel** [comment]
The only commit from last night was : dc7cd595d95b7b4257e3af595c50ae4701104377

The issue is on somewhere in M68Kdisasm.c where op->mem.index_size is not set correctly

Another sample
```
-   0:	3172 1ed3 d320 	movew %a2@(ffffffffffffffd3,%d1:l:8),%a0@(-11488)
+   0:	3172 1ed3 d320 	movew %a2@(ffffffffffffffd3,%d1:w:8),%a0@(-11488)
```

**Comment by emoon** [comment]
Alright. I will take another look at it.

**Comment by emoon** [comment]
I get this output when I try

```
****************
Platform: M68K
Code:0x31 0x72 0x1e 0xd3 0xd3 0x20
Disasm:
0x30672:	move.w	$d3(a2, d1.l), $d320(a0)
0x30678:
```

**Comment by emoon** [comment]
So I'm not sure how you are testing this but for me it works

**Comment by nplanel** [comment]
fixed in https://github.com/nplanel/capstone/commit/b2e3ff296fa15ec48b8b6a223cf6eaf6eae6a561
