### ISSUE TITLE
subq is not decoded

### ISSUE THREAD

**Issue by nplanel** [emoon/capstone#52]
```
-   0:	550f           	subqb #2,%sp
+   0:	550f           	.short 0x550f
```

**Comment by emoon** [comment]
actually this is an illegal instruction.

when subq is used on a0-a7 only .w and .l is allowed.

**Comment by nplanel** [comment]
Ok so all good :)
I have some reverse output as well, like objdump do .short and capstone output mnemonic ....

**Comment by nplanel** [comment]
It's may be part of coldfire as before push a new issue, I test by compiling the instruction and dump it again, and compare the results.
In short
```
echo $@ | m68k-atari-mint-as -o .a.out
m68k-atari-mint-objdump -D .a.out
```

**Comment by emoon** [comment]
Maybe. Just looked in the M68000PRM.df

![subq](https://cloud.githubusercontent.com/assets/350822/10219447/548511ea-683f-11e5-9527-5ab3414b2f72.PNG)

**Comment by nplanel** [comment]
I seen that and I agreed with your comment.
I just assume it's parts of Coldfire, but it's not, so gcc/as are just buggy in this toolchain.

For the futur implementation of Coldfire, here a good explanation of the diffs between 680x0 and Coldfire
http://microapl.com/Porting/ColdFire/cf_68k_diffs.html

**Comment by nplanel** [comment]
So not_a_bug => as/objdump bug
